name: "Github Actions Rise Team 2"

on: push 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install on frontend
      run: cd frontend && yarn install

    - name: npm install on backend
      run: cd .. && cd backend && npm install

    - name: Run Backend
      run: npm start

    - name: Run Frontend
      run: cd .. && cd frontend && yarn start
